### ISSUE TITLE
Port PID controller to contro joint using effort

### ISSUE THREAD

**Issue by ahcorde** [ros-controls/gz_ros2_control#306]
Related with this PR on gazebo_ros2_control https://github.com/ros-controls/gazebo_ros2_control/pull/294

**Comment by christophfroehlich** [comment]
There is a stale PR which already implemented something similar #122

**Comment by peci1** [comment]
As a workaround, pid_controller/PidController can be used explicitly (not sure about mimic joints, though).

```YAML
  controller_manager:
    ros__parameters:
      use_sim_time: True
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      diffdrive_controller:
        type: diff_drive_controller/DiffDriveController
      wheel_pids:
        type: pid_controller/PidController

  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: True
      update_rate: 100  # Hz

  diffdrive_controller:
    ros__parameters:
      use_sim_time: True
      left_wheel_names: ["wheel_pids/left_wheel_j"]
      right_wheel_names: ["wheel_pids/right_wheel_j"]
      # other options

  wheel_pids:
    ros__parameters:
      use_sim_time: True
      dof_names: ["left_wheel_j", "right_wheel_j"]
      command_interface: effort
      reference_and_state_interfaces: ["velocity", "effort"]
      gains:
        left_wheel_j: { p: 100.0, i: 0.1, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0 }
        right_wheel_j: { p: 100.0, i: 0.1, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0, feedforward_gain: 1.0 }
```

and the launch file:

```Python
def generate_launch_description():
    description_package = ...  # your robot description package
    control_params_file = PathJoinSubstitution([description_package, 'config', 'control.yaml'])

    diffdrive_controller_node = Node(
        package='controller_manager',
        executable='spawner',
        namespace="",  # Namespace is not pushed when used in EventHandler
        parameters=[control_params_file],
        arguments=[
            'diffdrive_controller',
            '-c',
            'controller_manager',
            '--controller-manager-timeout',
            '120'
        ],
        output='screen',
    )

    wheel_pids = Node(
        package='controller_manager',
        executable='spawner',
        namespace="",  # Namespace is not pushed when used in EventHandler
        parameters=[control_params_file],
        arguments=[
            'wheel_pids',
            '-c',
            'controller_manager',
            '--controller-manager-timeout',
            '120'
        ],
        output='screen',
    )

    joint_state_broadcaster_spawner = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            'joint_state_broadcaster',
            '-c',
            'controller_manager',
            '--controller-manager-timeout',
            '120'
        ],
        output='screen',
    )

    diffdrive_controller_callback = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=wheel_pids,
            on_exit=[diffdrive_controller_node],
        )
    )

    wheel_pids_callback = RegisterEventHandler(
        event_handler=OnProcessExit(
            target_action=joint_state_broadcaster_spawner,
            on_exit=[wheel_pids],
        )
    )

    ld = LaunchDescription(ARGUMENTS)
    ld.add_action(joint_state_broadcaster_spawner)
    ld.add_action(wheel_pids_callback)
    ld.add_action(diffdrive_controller_callback)
    return ld
```
