### ISSUE TITLE
Gazebo crashes on giving large cmd_vel velocities in mecanum_drive demo

### ISSUE THREAD

**Issue by Amronos** [ros-controls/gz_ros2_control#495]
**Describe the bug**
On giving huge cmd_vel velocities on the ``/cmd_vel`` the robot starts moving in very weird ways (to be expected if the wheel joints are being allowed to rotate that fast), and then Gazebo eventually crashes. This issue doesn't occur in diff_drive, the joints are simply blocked from rotating that fast. How are the joints blocked from rotating too fast in diff_drive but not in mecanum_drive?

**To Reproduce**
1. Run 
```
ros2 launch gz_ros2_control_demos mecanum_drive_example.launch.py
```
2. Open another terminal and run
```
ros2 topic pub --rate 10 /cmd_vel geometry_msgs/msg/TwistStamped "
twist:
  linear:
    x: 0.0
    y: 0.0
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 10000.0"
```

**Expected behavior**
The joints should be blocked from rotating that fast and the robot should move at normal speeds in normal ways.

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version Jazzy & Gazebo Harmonic
- I have built ``gz_ros2_control`` from source.
