### ISSUE TITLE
/odom is not published in diff_drive_example.launch.py

### ISSUE THREAD

**Issue by Kotochleb** [ros-controls/gz_ros2_control#50]
## Environment
* OS Version: Ubuntu 20.04 (osrf/ros:galactic-desktop docker)
* Source build
* Branch `galactic`
* Ignition Fortress

## Description
I've adapted this package to my URDF and so far, publishing `/cmd_vel` and feedback from `/joint_states` and `/tf` is working. On the other hand, for some reason, `/odom` is not being published by ros2 control even though the same config for a **diff_drive_controller** is working on a real hardware.

To ensure that, the problem is not related only to my configuration, I checked examples and the same thing happens in **diff_drive_example.launch.py** while running inside docker also from examples. Basically, publishing odometry does not work, no matter if the URDF from examples is or isn't modified. I am confused since from what I understand, if **joint_state_broadcaster** has data to publish **diff_drive_controller** should as well.

**Comment by destogl** [comment]
Is this behavior only inside docker or also on a native machine? I didn't get that from your comment.

Does `/odom` topic simply doesn't exist when using simulation?

**Comment by Kotochleb** [comment]
This behavior was present inside the Docker. I assumed, if it is happening purely within docker without Ignition on the host machine, it should behave the same way everywhere.
I tried to once again recreate the behavior, and it still does not work.
You can try it by adding this compose to the **Dockerfile** directory in the repository and running it with `docker compose up`.
``` yaml
services:
  gz_ros2_control_test:
    build: .
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ros2 launch ign_ros2_control_demos diff_drive_example.launch.py gui:=true
```

As a `/odom` topic, I really meant `/diff_drive_base_controller/odom`. It does exist, but it is empty.
The simulation is reacting to messages on `/diff_drive_base_controller/cmd_vel_unstamped` and TFs seem to be correct in the Rviz2.
