### ISSUE TITLE
Harware interfaces only get Infinite velocity values commanded on joint

### ISSUE THREAD

**Issue by JoelDeen820** [ros-controls/gz_ros2_control#90]
gazebo : gazebo fortress
ros distro : humble 
installed binaries: libigngazebo6

HI All,
I am working on implementing our mars rover project, and are getting the following error when all of the controllers are configured and active within ignition gazebo/gazebo. 
```
[ruby $(which ign) gazebo-1] [Err] [JointFeatures.cc:157] Invalid joint velocity value [inf] commanded on joint [1_drive_joint DOF 0]. The command will be ignored
```
This is happening for all joints (1-6). 
Is there something that I misconfigured, or missing within the URDF or config file? 
Could this be a problem with the fortress control implementation as I have only gotten this error on the fortress gazebo platform?

The URDF control features that I am using, along with the plugins
```xml
<xacro:macro name="drive_control_interface" params="wheel_num">
        <joint name="${wheel_num}_drive_joint">
            <command_interface name="velocity">
                <param name="min">-120</param>
                <param name="max">120</param>
                <param name="initial_value">0.0</param>
            </command_interface>
            <state_interface name="velocity"/>
            <!-- <state_interface name="position"/> -->
        </joint>
    </xacro:macro>

<xacro:macro name="gazebo_control">
        <ros2_control name="IgitionSystem" type="system">
            <hardware>
                <plugin>ign_ros2_control/IgnitionSystem</plugin>
            </hardware>
            <xacro:drive_control_interface wheel_num="1"/>
            <xacro:drive_control_interface wheel_num="2"/>
            <xacro:drive_control_interface wheel_num="3"/>
            <xacro:drive_control_interface wheel_num="4"/>
            <xacro:drive_control_interface wheel_num="5"/>
            <xacro:drive_control_interface wheel_num="6"/>
        </ros2_control>

        <gazebo>
            <plugin filename="ign_ros2_control-system" name="ign_ros2_control::IgnitionROS2ControlPlugin">
                <parameters>$(find rover_description)/config/rover_controller.yaml</parameters>
                <robot_param>robot_description</robot_param>
                <robot_param_node>robot_state_publisher</robot_param_node>
            </plugin>
       <gazebo>
</xacro:macro>
```
and the joint definitins is as follows
```xml
<joint name="${prefix}_drive_joint" type="continuous">
            <origin xyz="0.0 0.0 -0.07543" rpy="1.5707 0.0 0.0"/>
            <parent link="${prefix}_wheel_mount"/>
            <child link="${prefix}_wheel"/>
            <xacro:if value="${side == 'R'}">
                <axis xyz="0.0 0.0 1.0"/>
            </xacro:if>
            <xacro:if value="${side == 'L'}">
                <axis xyz="0.0 0.0 -1.0"/>
            </xacro:if>
            <limit effort="20.0" velocity="5.0"/>
        </joint>
```
Also the config file for the system
```yaml
differential_controller:
  ros__parameters:
    left_wheel_names: ["2_drive_joint"]
    right_wheel_names: ["1_drive_joint"]

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: rover_base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 1.0
    linear.x.min_jerk: -1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 1.0
    angular.z.min_jerk: -1.0
```

dockerfile for reference
```dockerfile
FROM osrf/ros:humble-desktop-full-jammy


ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

RUN apt-get update && apt-get -y upgrade

RUN apt-get update && apt-get -y install ros-${ROS_DISTRO}-ros2-control \ 
                                ros-${ROS_DISTRO}-ros2-controllers \
                                ros-${ROS_DISTRO}-ros-ign-gazebo \ 
                                libignition-gazebo6-dev \
                                ros-${ROS_DISTRO}-xacro

RUN mkdir -p /int_pkgs/src
RUN chown -R 1000:1000 /int_pkgs

COPY ./ros_entrypoint.sh /
RUN chmod +x /ros_entrypoint.sh

ENV IGNITION_VERSION=fortress
ENV GZ_VERSION=fortress

RUN mkdir -p /comp_pkg/src
WORKDIR /comp_pkg/src
RUN git clone https://github.com/gazebosim/ros_gz.git -b ${ROS_DISTRO}
RUN git clone https://github.com/ros-controls/gz_ros2_control.git
WORKDIR /comp_pkg
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && colcon build
